[program:docker-warning-heartbeat]
command = /app/bin/docker_warning_heartbeat
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
priority = 50
