#!/bin/sh
set -e

export PGPASSWORD="$POSTGRES_PASSWORD"

# Wait for database to get available
until psql -h "database" -U "$POSTGRES_USER" -c 'SELECT 1' > /dev/null 2>&1 ; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

unset PGPASSWD

>&2 echo "Postgres is up"

# Migrate database to current version and collect static files
if [ "x$1" = "xrunserver" ] ; then
    $START_CMD migrate
    $START_CMD collectstatic --noinput
fi

#start the daemon
exec $START_CMD "$@"
